var adPatternPC = [
  {
    id:'01',
    pattern:'Full Screen',
    describe:'进入网站后时首先看到的大块全屏广告。',
    position:[
      {
        id:'01',
        describe:'进入网站后时首先看到的大块全屏广告。'
      }
    ]
  },
  {
    id:'02',
    pattern:'Leaderboard',
    describe:'页面上部导航栏下方的长带状广告。注：如无特别说明，“页面”指所有常规页面，包括首页、频道页、文章页，下同。',
    position:[
      {
        id:'01',
        describe:'页面上部导航栏下方的长带状广告。'
      }
    ]
  },
  {
    id:'03',
    pattern:'Banner',
    describe:'页面中部穿插的长带状广告（页面导航栏下方的长带状广告除外，其叫做LeaderBoard，见上）。从上到下顺序出现。',
    position:[
      {
        id:'01',
        describe:'页面从上至下第一个Banner位。'
      },
      {
        id:'02',
        describe:'页面从上至下第二个Banner位。'
      },
      {
        id:'03',
        describe:'页面从上至下第三个Banner位。'
      }
    ] 
  },
  {
    id:'04',
    pattern:'MPU',
    describe:'页面中的块状广告。出现顺序为：右侧侧边栏从上至下排列，然后页面正文由上至下穿插',
    position:[
      {
        id:'01',
        describe:'页面右侧从上至下第1个MPU位。'
      },
      {
        id:'02',
        describe:'如页面右侧有两个MPU位, 则其为页面右侧从上至下排列的第2个MPU位；如页面右侧有且仅有一个MPU位，则其为页面正文由上至下穿插的第1个MPU位。'
      },
      {
        id:'03',
        describe:'如页面右侧有两个MPU位, 则其为页面正文由上至下穿插的第1个MPU位；如页面右侧有且仅有一个MPU位，则其为页面正文由上至下穿插的第2个MPU位。'
      },
      {
        id:'04',
        describe:'如页面右侧有两个MPU位, 则其为页面正文由上至下穿插的第2个MPU位。'
      }
    ]  
  },
  {
    id:'03',
    pattern:'Ribbon',
    describe:'短带状',
    position:[
      {
        id:'01',
        describe:'页面右侧栏顶部的短带状'
      }
    ]
  },
  
  {
    id:'06',
    pattern:'Text_Link',
    describe:'文字链。该Pattern可出现在页面右侧栏上部。',
    position:[
      {
        id:'01',
        describe:'页面右侧栏上部区域从上至下第一个Text_Link。'
      },
      {
        id:'02',
        describe:'页面右侧栏上部区域从上至下第一个Text_Link。'
      },
      {
        id:'03',
        describe:'页面右侧栏上部区域从上至下第一个Text_Link。'
      }
    ]
  },
  {
    id:'08',
    pattern:'Inread(1x1)',
    position:[
      {
        id:'01',
        describe:''
      }
    ]
  },
  {
    id:'09',
    pattern:'Inread ad_590*400',
    describe:'',
    position:[
      {
        id:'01',
        describe:''
      }
    ]
  },
  {
    id:'10',
    pattern:'Opening_AD',
    describe:'',
    position:[
      {
        id:'01',
        describe:''
      }
    ]
  },
  
  {
    id:'12',
    pattern:'Information_image',
    describe:'',
    position:[
      {
        id:'01',
        describe:''
      },
      {
        id:'02',
        describe:''
      }
    ]
  }
]

var adPatternPhone = [
  {
    id:'01',
    pattern:'Full Screen',
    describe:'进入手机端网站或App时看到的大块全屏广告。',
    position:[
      {
        id:'01',
        describe:'手机端网页形式的全屏广告。'
      },
      {
        id:'02',
        describe:'手机端原生形式的全屏广告。'
      }
    ]
  },
  {
    id:'03',
    pattern:'Banner',
    describe:'手机端页面顶部、底部的带状广告。',
    position:[
      {
        id:'01',
        describe:'手机端页面顶部的带状广告。'
      },
      {
        id:'02',
        describe:'手机端页面底部的带状广告。'
      }
    ] 
  },
  {
    id:'04',
    pattern:'MPU',
    describe:'页面中的块状广告。页面由上至下穿插。',
    position:[
      {
        id:'01',
        describe:'页面从上至下第1个MPU位。'
      },
      {
        id:'02',
        describe:'页面从上至下第2个MPU位。'
      }
    ]  
  }
]

var adPatternPad = [
  {
    id:'01',
    pattern:'Full Screen',
    describe:'进入pad网站或App时看到的大块全屏广告。',
    position:[
      {
        id:'01',
        describe:'pad端网页形式的全屏广告。'
      },
      {
        id:'02',
        describe:'pad端原生形式的全屏广告。'
      }
    ]
  },
  {
    id:'03',
    pattern:'Banner',
    describe:'pad端页面顶部横向、纵向的广告。',
    position:[
      {
        id:'01',
        describe:'pad端页面顶部的横向广告。'
      },
      {
        id:'02',
        describe:'pad端页面底部的纵向广告。'
      }
    ] 
  },
   {
    id:'04',
    pattern:'MPU',
    describe:'页面中的块状广告。页面由上至下穿插。',//QUEST,也应该是先排完右侧，再排中部。
    position:[
      {
        id:'01',
        describe:'页面从上至下第1个MPU位。'
      },
      {
        id:'02',
        describe:'页面从上至下第2个MPU位。'
      }
    ]  
  },
]